# Generated by Django 5.2 on 2025-05-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='experience',
            field=models.PositiveIntegerField(default=0, verbose_name='Стаж работы'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='doctors/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='category',
            field=models.IntegerField(choices=[(1, 'Вторая категория'), (2, 'Первая категория'), (3, 'Высшая категория')], verbose_name='Категория'),
        ),
    ]
