# Generated by Django 5.2 on 2025-05-01 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_remove_visit_diagnosis_visit_created_at_visit_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateField(verbose_name='Дата приема'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.doctor'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.patient'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.service'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтвержден'), ('completed', 'Завершен'), ('canceled', 'Отменен')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='visit',
            name='time',
            field=models.TimeField(verbose_name='Время приема'),
        ),
    ]
